name: Test MySQL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mysql:
    strategy:
      matrix:
        deno: ["v1.x"]
    runs-on: [ubuntu-latest]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2

      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"

      - uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Write new .env test file
        run: |
          echo "DB_PORT=${{ job.services.mysql.ports['3306'] }}" > ./.env
          echo "DB_USER=root" >> ./.env
          echo "DB_PASS=password" >> ./.env

      - name: Deno Tests
        run: deno test --unstable -A ./tests/units/
