name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        deno: ["v1.x"]
    runs-on: [ubuntu-latest]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2

      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"

      - name: Hello world
        run: echo Hello world $FIRST_NAME $middle_name $Last_Name!
        env:
          FIRST_NAME: Mona
          middle_name: The
          Last_Name: ${{ job.services.mysql.ports[3306] }}

      #- uses: denolib/setup-deno@v2
      #with:
      #   deno-version: ${{ matrix.deno }}

      #- name: Deno Tests
      #  run: deno test --unstable -A ./tests/units/
      #  env:
      #    DB_PORT: ${{ job.services.mysql.ports[3306] }}
