name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        deno: ["v1.x"]
    runs-on: [ubuntu-latest]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2

      - uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Deno Tests
        run: deno test --unstable -A ./tests/units/
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
